- name: add passenger key
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id='561F9B9CAC40B2F7' state=present

- name: add apt requirements for passenger
  apt: name='{{ item }}' state=present
  with_items:
    - apt-transport-https
    - ca-certificates
  
- name: add passenger repository
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main' state=present
  when: "ansible_distribution == 'Ubuntu'"
